project:
  type: book

book:
  title: Untitled dissertation template
  author:
    - name: Jane R. Doe
      email: jdoe@umich.edu
      orcid: 9999-9999-9999-9999
  date: last-modified
  date-format: YYYY
  output-file: dissertation
  chapters:
    - index.qmd
    - chapters/usage.qmd
    - chapters/discussion.qmd
    - references.qmd

dept: Mathematics
preface: |
  This dissertation is a sample document using the \texttt{rackham.cls}
  template.
dedication: |
  This manual is dedicated to all doctoral students at the University of
  Michigan's Horace H. Rackham School of Graduate Studies.

  Also to my plants.
acknowledgements: |
  This template has been modified by a lot of people over the years.
  To the best of my knowledge, it's original version was written by Jin Ji in
  1988.
  Modifications to it have since been made by Roque D.\ Oliveira in 1992,
  Jason Gilbert  in 2008, Derek Dalle in 2011, and Umang Varma in 2019.
  It is possible that other people have modified this document
  (in fact, there is a unattributed change in the changelog dated 1989.11.29).
abstract: |
  With walk through basic steps of using this \LaTeX\ template.
committee: # alphabetical order
  - Professor John D. Brown, Chair
  - Assistant Professor Charles Z. Jones
  - Associate Professor Kathleen X. Lee, Yale University
  - Associate Professor Horace H. Rackham
  - Professor Emeritus Ann A. Smith
chair: Professor John D. Brown
#cochair: Co-chair One & Co-chair Two
acronyms:
  \acro{TLA}{Three Letter Acronym}
  \acro{SOA}{Some Other Acronym}
frontispiece: frontispiece.png

bibliography: references.bib
fontsize: 12pt
format:
  rackham-pdf:
    keep-tex: true
    classoption:
      - thesis
